### ISSUE TITLE
使用archetype生成微服务模块是不是没法用Docker部署

### ISSUE THREAD

**Issue by reltian** [jeecgboot/jeecg-boot#4355]
##### 问题描述：
通过教程用archetype生成微服务模块，打成jar包，用java命令行直接运行没问题。用docker-compose部署之后，启动报错。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/28427965/205447773-98a3b92f-83cf-4c7e-b044-ace927050a5d.png)

docker-compose.yml 文件内容：
version: '2'
services:
  ywpt-module-ihr
:
    build:
      context: ./ywpt-module-ihr-start
    container_name: ywpt-ihr-start
    hostname: ywpt-module-ihr
    restart: on-failure
    environment:
      - TZ=Asia/Shanghai

Dockerfile  文件内容：
FROM anapsix/alpine-java:8_server-jre_unlimited

MAINTAINER jeecgos@163.com

RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

RUN mkdir -p /ywpt-module-ihr

WORKDIR /ywpt-module-ihr

EXPOSE 7070

ADD ./target/ywpt-module-ihr-start.jar ./

CMD sleep 10;java -Dfile.encoding=utf-8 -Djava.security.egd=file:/dev/./urandom -jar ywpt-module-ihr-start.jar

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
肯定可以用docker，你自己看看是不是配置写错了

**Comment by reltian** [comment]
配置应该没错吧，模仿system模块写的。


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月4日(周日) 下午4:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jeecgboot/jeecg-boot] 使用archetype生成微服务模块是不是没法用Docker部署 (Issue #4355)




 
肯定可以用docker，你自己看看是不是配置写错了
 
&mdash;

**Comment by zhangdaiscott** [comment]
截图看配置，做详细说明

**Comment by reltian** [comment]
docker-compose.yml 文件内容：
```
version: '2'
services:
  ywpt-module-ihr:
    build:
      context: ./ywpt-module-ihr-start
    container_name: ywpt-ihr-start
    hostname: ywpt-module-ihr
    restart: on-failure
    environment:
      - TZ=Asia/Shanghai
```

Dockerfile 文件内容：
```
FROM anapsix/alpine-java:8_server-jre_unlimited

MAINTAINER [jeecgos@163.com](mailto:jeecgos@163.com)

RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

RUN mkdir -p /ywpt-module-ihr

WORKDIR /ywpt-module-ihr

EXPOSE 7070

ADD ./target/ywpt-module-ihr-start.jar ./

CMD sleep 10;java -Dfile.encoding=utf-8 -Djava.security.egd=file:/dev/./urandom -jar ywpt-module-ihr-start.jar
```
