### ISSUE TITLE
druid配置项validationQuery不生效

### ISSUE THREAD

**Issue by 99swiftlife** [jeecgboot/jeecg-boot#5679]
##### 版本号：
3.5.0

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
druid多数据源添加postgresql配置，在新建模块中调用MybatisPlus提供的save方法时，报错，
断点调试发现 validationQuery配置不生效，一直是SELECT 1 FROM DUAL，与所填SELECT 1不符，
修改其余的initial-size配置也不生效
dev 配置：
```yaml
spring:
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: 123456
        allow:
      web-stat-filter:
        enabled: true
    dynamic:
      druid: # 全局druid参数，绝大部分值和默认保持一致。(现已支持的参数如下,不清楚含义不要乱设置)
        # 连接池的配置信息
        # 初始化大小，最小，最大
        initial-size: 5
        min-idle: 5
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/jeecg-boot?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
        # 多数据源配置
        postgres:
          url: jdbc:postgresql://127.0.0.1:5432/rss_sample_center
          username: postgres
          password: 123456
          driver-class-name: org.postgresql.Driver
```

##### 截图&代码：
报错：
![image](https://github.com/jeecgboot/jeecg-boot/assets/73336290/5c79eee3-f778-4b73-8229-89540a094c9c)
断点调试查看validationQuery项：
![image](https://github.com/jeecgboot/jeecg-boot/assets/73336290/40d9dc38-5081-4941-9606-06d31e281263)
代码：
controller中调用默认的save方法：
```java
	@ApiOperation(value = "save", notes = "写入样本元数据")
	@PostMapping(value = "/save")
	public boolean saveSample(@RequestBody SCOpticalSample rsSample) {
		log.info(" ------ ");
		return jeecgHelloService.save(rsSample);
	}
```

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
