### ISSUE TITLE
分别部署mysq容器和nacos容器，nacos启动错误

### ISSUE THREAD

**Issue by 99swiftlife** [jeecgboot/jeecg-boot#6015]
##### 版本号：
3.5.1

##### 前端版本：
vue3版

##### 问题描述：
将本地构建的jeecg-boot-mysql、redis等数据库镜像和nacos、gataway、system等镜像分别部署至两台linux服务器上，本地和linux服务器上均配置了/etc/hosts，发现nacos容器内部无法解析jeecg-boot-mysql，导致无法找到数据库从而无法启动（在本地采用相同镜像构建nacos，只将mysql容器置于远程服务器上时则能够正常启动，容器内能解析jeecg-boot-mysql）

##### 截图&代码：
本地镜像通过docker save导出并传输到远程服务器上，并通过docker load -i 加载镜像
然后再远程服务器上采用修改后的docker-compose.yml使其从已有镜像创建容器：
```yaml
version: '2'
services:
  jeecg-boot-nacos:
    restart: always
    image: jeecg-server-cloud_jeecg-boot-nacos:latest
    ports:
      - 8848:8848
    container_name: jeecg-boot-nacos
    hostname: jeecg-boot-nacos

  jeecg-boot-system:
    depends_on:
      - jeecg-boot-nacos
    image: jeecg-server-cloud_jeecg-boot-system:latest
    container_name: jeecg-system-start
    hostname: jeecg-boot-system
    restart: on-failure
    environment:
      - TZ=Asia/Shanghai

  jeecg-boot-gateway:
    restart: on-failure
    image: jeecg-server-cloud_jeecg-boot-gateway:latest
    ports:
      - 9999:9999
    depends_on:
      - jeecg-boot-nacos
      - jeecg-boot-system
    container_name: jeecg-boot-gateway
    hostname: jeecg-boot-gateway

#  jeecg-boot-sentinel:
#    restart: on-failure
#    build:
#      context: ./jeecg-visual/jeecg-cloud-sentinel
#    ports:
#      - 9000:9000
#    depends_on:
#      - jeecg-boot-nacos
#      - jeecg-boot-demo
#      - jeecg-boot-system
#      - jeecg-boot-gateway
#    container_name: jeecg-boot-sentinel
#    hostname: jeecg-boot-sentinel
#
#  jeecg-boot-xxljob:
#    build:
#      context: ./jeecg-visual/jeecg-cloud-xxljob
#    ports:
#      - 9080:9080
#    container_name: jeecg-boot-xxljob
#    hostname: jeecg-boot-xxljob
```
远程服务器/etc/hosts:
```
10.3.1.151 jeecg-boot-mysql
10.3.1.151 jeecg-boot-redis
10.3.1.151 neo4j-apoc
10.3.1.151 postgis
10.3.1.153 jeecg-boot-nacos
10.3.1.153 jeecg-boot-system
10.3.1.153 jeecg-boot-gateway
```

nacos.log截图
<img width="590" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/73336290/50ece63c-e56c-4089-b4d7-81e9a4e08ab3">
<img width="994" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/73336290/04036a06-9a99-4c25-89e8-edfad452b5f0">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
