### ISSUE TITLE
更改jeecg_database.properties数据库链接不生效

### ISSUE THREAD

**Issue by shr2556** [jeecgboot/jeecg-boot#6308]
##### 截图&代码：
=========================================
```
jeecg_database.prpperties:
diver_name=com.mysql.jdbc.Driver
url=jdbc:mysql://localhost:3306/xbshop_shijiebox?useUnicode=true&characterEncoding=UTF-8
username=root
password=root
database_name=xbshop_shijiebox
```
=========================================
application数据源部分配置:
```
datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/zeroy_sxb_boot?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
          # 多数据源配置
        shop:
          url: jdbc:mysql://localhost:3306/xbshop_shijiebox?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
```

![QQ截图20240613161319](https://github.com/jeecgboot/jeecg-boot/assets/67695752/b8839b75-c336-4d86-874e-f86753d97627)
